name: book_tiket
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  fluentui_icons: ^1.0.0
  intl: ^0.18.0
  salomon_bottom_bar: ^3.3.1
  font_awesome_flutter: ^10.4.0
  get:
  barcode: ^2.2.3
  google_fonts: ^3.0.1
  unicons: ^2.1.0
  slide_drawer: ^1.0.3
  syncfusion_flutter_datepicker: ^21.1.35
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.2.1
  animated_snack_bar: ^0.3.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  barcode_widget: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
fonts:
  - family: lato
    fonts:
      - asset: assets/font/Lato/Lato-Black.ttf
      - asset: assets/font/Lato/Lato-BlackItalic.ttf
      - asset: assets/font/Lato/Lato-Bold.ttf
      - asset: assets/font/Lato/Lato-BoldItalic.ttf
      - asset: assets/font/Lato/Lato-Italic.ttf
      - asset: assets/font/Lato/Lato-Light.ttf
      - asset: assets/font/Lato/Lato-LightItalic.ttf
      - asset: assets/font/Lato/Lato-Regular.ttf
      - asset: assets/font/Lato/Lato-Thin.ttf
      - asset: assets/font/Lato/Lato-ThinItalic.ttf
        style: italic
